#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# killall stats_provider
# # Update with path to stats_provider
# $CONFIG_DIR/sketchybar-system-stats/target/release/stats_provider --cpu usage --disk usage --memory ram_usage &





##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top \
                  height=40 \
                  blur_radius=10 \
                  color=none \
                  margin=-12 \
                  y_offset=5 \
                  corner_radius=5 \
                  # border_width=2 \
                  # border_color=0xff6D727A
                  # display="main"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
   icon.font="IBM Plex Mono:Medium:15.0" 
  label.font="IBM Plex Mono:Medium:15.0"
  # icon.font="SF Pro:Semibold:15.0" 
  # label.font="SF Pro:Semibold:15.0"
  background.color=$ITEM_BG_COLOR      
  background.corner_radius=5            \
  background.height=24      
  icon.color=$TEXT_COLOR
  label.color=$TEXT_COLOR
  # icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  # label.padding_right=4
  label.padding_right=10                \
  icon.padding_left=10   
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# sketchybar --add item chevron left \
#            --set chevron icon= label.drawing=off \
#            --add item front_app left \
#            --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
#            --subscribe front_app front_app_switched



##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

# Left side items

source $ITEM_DIR/spaces.sh


# right side items

# Right side items
# -- Right Side Of Notch Items --
source $ITEM_DIR/calendar.sh
# sketchybar --add item separator right \
#            --set separator \
#            icon="│" \
#            icon.color=$TEXT_COLOR \
#            	icon.font="Hack Nerd Font Mono:regular:18.0" \
#            label.drawing=off \
#            background.color=none \
#            icon.padding_right=14
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

source $ITEM_DIR/front_app.sh


# sketchybar --add item clock right \
#            --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
#            --add item volume right \
#            --set volume script="$PLUGIN_DIR/volume.sh" \
#            --subscribe volume volume_change \
#            --add item battery right \
#            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#            --subscribe battery system_woke power_source_change

# Add the aerospace_workspace_change event we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change


# Add workspaces for all monitors
for monitor in $(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id}"); do
  for sid in $(aerospace list-workspaces --monitor "$monitor"); do
    # display_id="1"
    # Determine which display this workspace should be shown on
    # if [ "$sid" -ge 8 ] && [ "$sid" -le 9 ]; then
    #   display_id="5"
    # fi

   # If sid equals 1, skip adding it to the bar
    if [ "$sid" -eq 1 ]; then
      continue  # Skip this iteration and don't display it
    fi
    # if [ "$sid" -eq "X" ]; then


    
    sketchybar --add item space.$sid left \
      --set space.$sid display="$display_id" \
      --subscribe space.$sid aerospace_workspace_change \
      --set space.$sid \
      drawing=on \
      background.color=0x44ffffff \
      background.corner_radius=5 \
      background.drawing=on \
      background.border_color=0xAAFFFFFF \
      background.border_width=0 \
      background.height=25 \
      icon="$sid" \
      icon.padding_left=10 \
      icon.shadow.distance=4 \
         icon.font="IBM Plex Mono:Bold:15.0"  \
      icon.shadow.color=0xA0000000 \
      label.font="sketchybar-app-font:Regular:16.0" \
      label.padding_right=20 \
      label.padding_left=0 \
      label.y_offset=-1 \
      label.shadow.drawing=off \
      label.shadow.color=0xA0000000 \
      label.shadow.distance=4 \
      click_script="aerospace workspace $sid" \
      script="$CONFIG_DIR/plugins/aerospace.sh $sid"
  done
done

# Load Icons on startup for all monitors
for monitor in $(aerospace list-monitors); do
  for sid in $(aerospace list-workspaces --monitor "$monitor" --empty no); do
    apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

    sketchybar --set space.$sid drawing=on

    icon_strip=" "
    if [ "${apps}" != "" ]; then
      while read -r app; do
        icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
      done <<<"${apps}"
    else
      icon_strip=""
    fi
    sketchybar --set space.$sid label="$icon_strip"
  done
done

source $ITEM_DIR/media.sh
source "$PLUGIN_DIR/stats/item.sh"

bluetooth_audio=(
  script="$CONFIG_DIR/plugins/bluetooth_audio.sh"
  icon.font="Hack Nerd Font:Bold:16.0"
  icon.padding_right=4
  icon=󰋋
  label.font="SF Pro:Semibold:13.0"
  label.padding_right=8
  update_freq=3
)

sketchybar --add item bluetooth_audio right \
           --set bluetooth_audio "${bluetooth_audio[@]}" \
                           icon.font="Hack Nerd Font Mono:regular:22.0" \
           background.color=none \
           --subscribe bluetooth_audio system_woke

sketchybar --add item bluetooth right \
           --set bluetooth \
                script="~/.config/sketchybar/plugins/bluetooth.sh" \
                update_freq=5 \
                icon=󰂯 \
                background.color=none \
                icon.font="Hack Nerd Font Mono:regular:18.0" \
                icon.padding_left=30 \
           --subscribe bluetooth system_woke


sketchybar --add item space_separator left \
           --set space_separator \
           icon="│" \
           icon.color=$TEXT_COLOR \
           	icon.font="Hack Nerd Font Mono:regular:18.0" \
           label.drawing=off \
           background.color=none \
           icon.padding_right=0 \
           icon.padding_left=0

# Add a bracket around all workspace items
sketchybar --add bracket workspaces calendar '/space\..*/' space_separator \
           --set workspaces \
           background.border_color=$BRACKET_BORDER\
           background.border_width=2 \
           background.corner_radius=8 \
           background.height=40 \
           background.padding_left=20 \
           background.padding_right=20 \
           padding_left=20 \
           background.color=$BRACKET_BACKGROUND \

           # Add a bracket around all workspace items
sketchybar --add bracket secondo volume separator_right front_app battery memory cpu.percent bluetooth \
           --set secondo \
           background.border_color=$BRACKET_BORDER\
           background.border_width=2 \
           background.corner_radius=8 \
           background.height=40 \
           background.padding_left=20 \
           background.padding_right=20 \
           padding_left=20 \
           background.color=$BRACKET_BACKGROUND

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
